# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8983f1b56475d1070822e4499f041dff72ca032a09ce86111aeb219a1607e02ee0e80b305134c27dbfea19338cf4afa81d66c8212186120aa2cb9f03a8f9ba6e

test:
  secret_key_base: 4284e8565a12a83ec36a4adde0c59685a219673cc41f79dd6db891473cb07872c5ab05e7e9f1274873080fd73efd1f5a022b8b3524e8db31634ce97b4ddc97b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
